name: Build and Deploy to Azure App Service
 
on:
  push:
    branches:
      - main
    paths:
      - './weatherapi/cicdapi/**'
      
env:
  SOLUTION_LOCATION: './weatherapi/weatherapi.sln'
  PROJECT_LOCATION: './weatherapi'
  APPLICATION_NAME: 'tapcicdapi'
 
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Build
        run: dotnet build ${{ env.SOLUTION_LOCATION }} -c Release
      - name: Publish
        run: dotnet publish ${{ env.PROJECT_LOCATION }} -c Release -o ${{ github.workspace }}/

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: output
          path: ${{ github.workspace }}/

 
  deploy:
    runs-on: windows-latest
    needs: build
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: output

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.APPLICATION_NAME }}
          slot-name: 'Production'
          publish-profile: ${{ secrets.CICDSECRET }}
          package: ${{ github.workspace }}/
